class ballincrosshair : CustomCrosshair {
    ui TextureID dotTex, dot6Tex, dot7Tex, dot8Tex, dot9Tex;

    const ZOOM_TIME = 0.21;
    const INNER_UV = 201. / 256.;
    const OUTER_UV = 213. / 256.;

    const FIRE_TIME = 0.15;

    ui CircleShape32 circle;
    
    override void init() {
        Super.init();
    }

    override void uiInit() {
        Super.uiInit();

        dotTex  = getReady("XH_DOT1");
		dot6Tex = getReady("XH_DOT6");
        dot7Tex = getReady("XH_DOT7");
		dot8Tex = getReady("XH_DOT8");
        dot9Tex = getReady("XH_DOT9");
        circle.init("XH_CIRC9", 120, 12, INNER_UV, OUTER_UV);
        makeTexReady(circle.tex.texID);
    }

    override void attach(SelacoWeapon weapon) {
        Super.attach(weapon);
    }

    override void detach() {
        Super.detach();
    }

    override void tick() {
		if(!weapon || !weapon.owner)
			return;
        Super.tick();
    }

    override double getHeight() {
        return virtualScreenSize.y ? (screenSize.y / virtualScreenSize.y) * (spread > 3 ? 140.0 : 100) : 0;
    }

    override void draw(double fracTic, double alpha, Vector2 offset) { 
        if(!weapon) return;

        if(!isReady && !(
            TexMan.MakeReady(dotTex) &&
			TexMan.MakeReady(dot6Tex) &&
            TexMan.MakeReady(dot7Tex) &&
			TexMan.MakeReady(dot8Tex) &&
            TexMan.MakeReady(dot9Tex) &&
            TexMan.MakeReady(circle.tex.texID)
        )) return;
        isReady = true;
        
        Color crosscolor = crosshaircolor;
        Color col   = Color(255, crosscolor.r, crosscolor.g, crosscolor.b);
        Color col2  = Color(255, crosscolor.b, crosscolor.g, crosscolor.r);
        Vector2 scScale = getVirtualScreenScale();
        Vector2 center = (screenSize * 0.5) + offset;

        double time = (double(level.TotalTime) + fracTic) * ITICKRATE;
        //double zoomTime = (double(level.TotalTime - zoomTick) + fracTic) * ITICKRATE;
        //double zoomFactor = CLAMP(zoomTime / ZOOM_TIME, 0.0, 1.0);
        double fireDelta = 1.0 - CLAMP( ((double(level.TotalTime - fireTick) + fracTic) * ITICKRATE) / FIRE_TIME, 0.0, 1.0);
        //if(!zooming) zoomFactor = 1.0 - zoomFactor;

        //double spreadVal = UIMath.EaseInQuadF( UIMath.Lerpd(deltaSpread, spread, fracTic) / 4.0 );
        double spreadVal = UIMath.EaseInQuadF((UIMath.Lerpd(deltaSpread, spread, fracTic) - 0.9) / (4.0 - 0.9));
        spreadVal += spreadVal * (0.35 * stunnedFactor);
        spreadVal -= spreadVal * (0.45 * (hoppingFactor));
        double circleRadius = UIMath.Lerpd(40, 120, spreadVal);// * (1.  + (zoomFactor * 0.5));
        

        circle.setRadius(circleRadius + (fireDelta * 5.), 12);
        circle.draw(center, scScale, col2, alpha);

        // Draw dot
        DrawXTex(dotTex, (0,0), 0, a: alpha, color: col, center: (0.5, 0.5));
		
		// Draw ammo
//            double eachSpace = 60. / double(weapon.Ammo2.maxAmount + 1);

			double eachSpace = 60. / double(3);
            for(int x = 0; x < 1; x++) {
                DrawXTex((weapon.owner.countinv("ReboundCatchbonus") > 1) > x ? dot9Tex : dot8Tex, (-65 + (eachSpace * (2 - x)), 70) + offset, 0, a: alpha * 0.75, color: col, center: (-3.1, 1));
            }
			
            for(int x = 0; x < 1; x++) {
                DrawXTex((weapon.owner.countinv("ReboundCatchbonus") > 50) > x ? dot9Tex : dot8Tex, (-45 + (eachSpace * (2 - x)), 70) + offset, 0, a: alpha * 0.75, color: col, center: (-3.1, 1));
            }
			
            for(int x = 0; x < 1; x++) {
                DrawXTex((weapon.owner.countinv("ReboundCatchbonus") > 100) > x ? dot9Tex : dot8Tex, (-25 + (eachSpace * (2 - x)), 70) + offset, 0, a: alpha * 0.75, color: col, center: (-3.1, 1));
            }
			
            for(int x = 0; x < 1; x++) {
                DrawXTex((weapon.owner.countinv("ReboundCatchbonus") > 150) > x ? dot7Tex : dot6Tex, (-5 + (eachSpace * (2 - x)), 70) + offset, 0, a: alpha * 0.75, color: col, center: (-3.1, 1));
            }


        // left hand ammo drawing

			for(int x = 0; x < 1; x++) {
                DrawXTex((weapon.owner.countinv("ReboundCatchbonus") > 1) > x ? dot9Tex : dot8Tex, (-65 + (eachSpace * (2 - x)), 70) + offset, 0, a: alpha * 0.75, color: col, center: (1, 1));
            }
			
			for(int x = 0; x < 1; x++) {
                DrawXTex((weapon.owner.countinv("ReboundCatchbonus") > 50) > x ? dot9Tex : dot8Tex, (-85 + (eachSpace * (2 - x)), 70) + offset, 0, a: alpha * 0.75, color: col, center: (1, 1));
            }
			
			for(int x = 0; x < 1; x++) {
                DrawXTex((weapon.owner.countinv("ReboundCatchbonus") > 100) > x ? dot9Tex : dot8Tex, (-105 + (eachSpace * (2 - x)), 70) + offset, 0, a: alpha * 0.75, color: col, center: (1, 1));
            }
			
			for(int x = 0; x < 1; x++) {
                DrawXTex((weapon.owner.countinv("ReboundCatchbonus") > 150) > x ? dot7Tex : dot6Tex, (-125 + (eachSpace * (2 - x)), 70) + offset, 0, a: alpha * 0.75, color: col, center: (1, 1));
            }

    }

    override void uiTick() {
        Super.uiTick();


    }
}